baseURL: "https://ruihusky.github.io/ruihusky/"
title: ruihusky's Blog
copyright: ruihusky's Blog
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ruihusky's Blog
  description: "ruihusky's Blog - https://ruihusky.github.io/ruihusky/"
  keywords: [ruihusky, 技术博客, 个人博客]
  # author: ruihusky
  DateFormat: "2006年1月2日"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
  # https://gohugo.io/getting-started/configuration-markup#highlight
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    style: dracula
    tabWidth: 2

defaultContentLanguage: zh
languages:
  zh:
    languageName: "Chinese"
    weight: 1
    menu:
      main:
        - name: Archives
          url: archives
          weight: 1
        - name: Categories
          url: categories
          weight: 2
        - name: Tags
          url: tags/
          weight: 3
        - name: Search
          url: search/
          weight: 4
